export default {
    SET_LOADING: 'SET_LOADING',
    SET_COUNTRY: 'SET_COUNTRY',
    SET_CITY: 'SET_CITY',
    SET_USER: 'SET_USER',
    SET_USER_CITY: 'SET_USER_CITY',
    DELETE_USER: 'DELETE_USER',
    SET_CUR_VER: 'SET_CUR_VER'
}